package br.unipar.plano.domain.reembolso.model

enum class  EnumEstados {
    AMAZONAS,
    ALAGOAS,
    ACRE,
    AMAPA,
    BAHIA,
    PARA,
    MATO_GROSSO,
    MINAS_GERAIS,
    MATO_GROSSO_DO_SUL,
    GOIAS,
    MARANHAO,
    RIO_GRANDE_DO_SUL,
    TOCANTINS,
    PIAUI,
    SAO_PAULO,
    RONDONIA,
    RORAIMA,
    PARANA,
    CEARA,
    PERNAMBUCO,
    SANTA_CATARINA,
    PARAIBA,
    RIO_GRANDE_DO_NORTE,
    ESPIRITO_SANTO,
    RIO_DE_JANEIRO,
    SERGIPE,
    DISTRITO_FEDERAL;
}